export PS1=" |\n\[\033[0;1;4;33m\] |                                                                                                   \r\[\033[0m\] |\[\033[1;33m\] \w \n \[\033[0m\]|\[\033[1;33m\] go-dev \t => \[\033[0m\]"
export PS2=" | \[\033[1;33m\]go-dev \t => \[\033[0m\]"

export DEV_DIR=/go-dev

# create ~/.ssh directory from ~/.ssh-orig and ~/.ssh-config
mkdir -p ~/.ssh
cp ~/.ssh-orig/* ~/.ssh
cp ~/.ssh-config ~/.ssh/config
